### ISSUE TITLE
Frontend for assigning completion goals to roadmaps/procedures 

### ISSUE THREAD

**Issue by kdorcey** [UIOWA5830SP19/SPP400#124]
The roadmap/procedure creation pages should have an element for assigning how many days/weeks/months a specific roadmap/procedure will take. If a roadmap that is assigned to a patient is not one of the premade generic roadmaps the user should have to input a new estimate.

**Comment by GregMalicki** [comment]
"If a roadmap that is assigned to a patient is not one of the premade generic roadmaps the user should have to input a new estimate."
----
I do not think we can do this yet, can we?
