### ISSUE TITLE
Model for average time to completion 

### ISSUE THREAD

**Issue by kdorcey** [UIOWA5830SP19/SPP400#150]
Each procedure should have a calculated "average time to completion" field. This should return a number of days/weeks that represents the average amount of time it took patients to complete this issue.

**Comment by GregMalicki** [comment]
I think i may have accidentally done this while working on something else, it isnt a part of the procedure model but a static function in assignedprocedures that takes in a procedure id and returns the average days to completion. gonna move this to done for now until further review
