### ISSUE TITLE
Reorganize workflow file structure

### ISSUE THREAD

**Issue by evan-meyer** [UIOWA5830SP19/SPP400#62]
The workflow app is currently inside of the inner SPP400 folder but should be outside of this folder like the other apps in the project. SPP400 urls.py will need to be updated to path to the new urls.py in workflow.

**Comment by evan-meyer** [comment]
Created new branch `workflow_structure` to reorganize the current file structure.

**Comment by evan-meyer** [comment]
Project has been restructured so that workflow is now it's own app. Page flow is not broken. Test coverage remains at 92% and no tests failed. Awaiting reviews for pull request.

**Comment by kdorcey** [comment]
Merge complete and successfully deployed to AWS!
