### ISSUE TITLE
Create model for linking patients and procedures 

### ISSUE THREAD

**Issue by evan-meyer** [UIOWA5830SP19/SPP400#67]
Create the model for linking patients and procedures. The model should join the primary keys of patients/procedures. It should have a row for the procedure "roadmap", a number representing which step of the procedure this entry is, a boolean flag for whether this procedure is based on a prior one, and an "expiration date".

**Comment by evan-meyer** [comment]
Made a branch called `workflow_model` to work on step linking. 

https://github.com/viewflow/cookbook

^Seems to be a decent resource for working with more modular flows and views.

**Comment by evan-meyer** [comment]
Some links I have been using to make new formsets:
https://medium.com/@taranjeet/adding-forms-dynamically-to-a-django-formset-375f1090c2b0
^scroll to third example
https://github.com/taranjeet/django-library-app
^github repo that article references

**Comment by kdorcey** [comment]
As we've decided to remove viewflow from the app the points and priority of this issue have been reduced. This should now be for creating the model for connecting patients+procedures

**Comment by evan-meyer** [comment]
Updated both the Patients and Procedures Models as building a new model doesn't seem dynamic enough for what will happen with the roadmaps.
