### ISSUE TITLE
Create landing pages for patients and procedures

### ISSUE THREAD

**Issue by evan-meyer** [UIOWA5830SP19/SPP400#70]
Clicking on the "patients" sidebar should link to the patient "landing" page. This page should have a list of each patient currently stored in the "patients" table with their name as a hyperlink. Clicking the hyperlink should route the user to that patients page which will display all of that patients information. The landing page should also have a button that routes to the form to create a new patient

Clicking the "procedure" sidebar button should be identical but for "procedures" instead of "patients".

**Comment by kdorcey** [comment]
As we have now better defined our minimum viable product I have changed this issue to one that better reflects our goals for this sprint.
